import "./globals.css";
import Nav from "./nav";
import { ThemeProvider } from "../components/muitailwind";
import { Poppins } from 'next/font/google'
const poppins = Poppins({ subsets: ['latin'], weight: ['500'], })

export const metadata = {
  title: "Personalize",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={poppins.className}>
         
        <div className="flex gap-10" >
  
  <Nav/>
  {children}
   </div>
          
        </body>
      </ThemeProvider>

    </html>
  );
}
